### PR TITLE
added: supported language French to readme

### PR DESCRIPTION
**Pull request by devmount**

### CODE REVIEW

**Comment by janmarkuslanger** [comment]
I did this just a minute before :D

**Comment by janmarkuslanger** [comment]
But thank you very much for your help!

**Comment by devmount** [comment]
I see, just forgot it in my initial pr and thought I directly add it ;)
You're welcome. Thanks for listing me in the contributors sections. If you want, you can link the names in this list to their corresponding GitHub profiles so that people can directly find the contributors on GitHub. Just an idea ;) Keep up the good work 👍

**Comment by janmarkuslanger** [comment]
I linked your profile :)

**Pull request closed without merging**
